allowBuilds:
  esbuild: true
  llama.rn: true
  node-datachannel: true
  react-native-enriched-markdown: true
  unrs-resolver: true
blockExoticSubdeps: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.3.0
overrides:
  "@voidzero-dev/vite-plus-core": 0.3.0
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
