allowBuilds:
  esbuild: true
  llama.rn: true
  unrs-resolver: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.3.0
overrides:
  vite: "catalog:"
  "@voidzero-dev/vite-plus-core": 0.3.0
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
